#!/bin/sh
# install - install a program, script, or datafile

scriptversion=2017-06-09; #UTC

# This originates from X11R5 (mit/util/scripts/install.sh), which was
# later released in X11R6 (xc/config/util/install.sh) with the
# following copyright and license.
#
# Copyright (C) 1994 X Consortium
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNEC-
# TION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name of the X Consortium shall not
# be used in advertising or otherwise to promote the sale, use or other deal-
# ings in this Software without prior written authorization from the X Consor-
# tium.
#
#
# FSF changes to this file are in the public domain.
#
# Calling this script install-sh is preferred over install.sh, to prevent
# `make' implicit rules from creating a file called install from it
# when there is no Makefile.
#
# This script is compatible with the BSD install script, but was written
# from scratch.

# set DOITPROG to echo to test this script

# Don't use :- since 4.3BSD and earlier shells don't like it.
doit="${DOITPROG-}"


PACKAGE='ecam_tk1_guvcview 1.7.2'
VERSION='g5d361af'

# put in absolute paths if you don't have them in your path; or use env. vars.

mvprog="${MVPROG-mv}"
cpprog="${CPPROG-cp}"
chmodprog="${CHMODPROG-chmod}"
chownprog="${CHOWNPROG-chown}"
chgrpprog="${CHGRPPROG-chgrp}"
stripprog="${STRIPPROG-strip}"
rmprog="${RMPROG-rm}"
mkdirprog="${MKDIRPROG-mkdir}"

transformbasename=""
transform_arg=""
instcmd="$mvprog"
chmodcmd="$chmodprog 0755"
chowncmd=""
chgrpcmd=""
stripcmd=""
rmcmd="$rmprog -f"
mvcmd="$mvprog"
src=""
dst=""
dir_arg=""

while [ x"$1" != x ]; do
    case $1 in

	--version) echo "$0 scriptversion=$scriptversion; PACKAGE VERSION = $PACKAGE-$VERSION"; exit $?;;

    esac
    shift
done

prefix="/usr/local/ecam_tk1"
bindir="${prefix}/bin"
datadir="${prefix}"
sharedir="${datadir}/share"


BIN_PROGRAM="ecam_tk1_guvcview"
currentdir="$PWD"
MKDIR_P="/bin/mkdir -p"
INSTALL="/usr/bin/install -c"
INSTALL_PROGRAM="${INSTALL}"

echo "$0 scriptversion=$scriptversion; PACKAGE VERSION = $PACKAGE-$VERSION";

#Remove binary from the prefix
if test -d "$bindir"; then
    list='ecam_tk1_guvcview'; test -n "$bindir" || list=;
    files=`for p in $list; do echo $p; done | sed -e 's|^.*/||'`;
    test -n "$files" || exit 0; 
    echo " cd $bindir && rm -f $files";
    cd "$bindir" && rm -f $files;
fi


#Install the binary from the current path to the prefix
echo "test -z "$bindir" || $MKDIR_P "$bindir" ";
test -z "$bindir" || $MKDIR_P "$bindir";
echo " $INSTALL_PROGRAM $currentdir/bin/$BIN_PROGRAM $bindir";
$INSTALL_PROGRAM $currentdir/bin/$BIN_PROGRAM $bindir;


#Remove share folder and re-install it
test -d "$sharedir" || rm -rf $sharedir;
echo " cp -r $currentdir/share $datadir";
cp -r $currentdir/share $datadir;

